import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ReactFlow, Background, Controls, MiniMap, ReactFlowProvider, Handle, Position, addEdge, reconnectEdge, useEdgesState, useNodesState, type Connection, type Edge, type NodeProps, type Viewport } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import "./canvas-overrides.css";
import * as api from "./api";
import type { ActionTestResult, Json, ProjectFolder, WorkflowSummary, Worker } from "./api";
import { actionReferenceFor, actionReferenceValue, autoLayout, findDanglingActionReferences, findDanglingEdges, graphToWorkflow, setActionReference, syncActionReferenceEdge, upstreamReferenceNodes, wouldCycle, workflowToGraph, type GraphNode, type GraphNodeData } from "./graph";

type Page = "home" | "repositories" | "workflows" | "executions" | "workers" | "plugins";
const nav: { id: Page; label: string; icon: string }[] = [
  { id: "home", label: "Home", icon: "⌂" }, { id: "repositories", label: "Repositories", icon: "▣" }, { id: "workflows", label: "Workflows", icon: "◇" },
  { id: "executions", label: "Executions", icon: "≡" }, { id: "workers", label: "Workers", icon: "⚙" }, { id: "plugins", label: "Plugins", icon: "⬡" },
];
const statusClass = (status?: string) => `status status-${String(status ?? "unknown").toLowerCase().replace(/[^a-z]/g, "-")}`;
const time = (value?: string) => value ? new Date(value).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "—";

type CatalogEntry = { kind?: string; use?: string; schema?: Json; configSchema?: Json; matchSchema?: Json; presentation?: { name?: string; description?: string; category?: string }; health?: string; };

/** Accept the current catalog contract as well as the old schemas map. */
function catalogEntries(catalog: Json): CatalogEntry[] {
  if (Array.isArray(catalog.entries)) return catalog.entries as CatalogEntry[];
  const values = catalog.schemas && typeof catalog.schemas === "object" ? Object.values(catalog.schemas) : Object.values(catalog);
  return values.filter((entry): entry is CatalogEntry => Boolean(entry && typeof entry === "object"));
}

function entrySchema(entry?: CatalogEntry, kind?: string): Json | undefined { return kind === "source" ? (entry?.matchSchema ?? entry?.schema ?? entry?.configSchema) : (entry?.schema ?? entry?.configSchema); }

function friendlyUseLabel(use: string): string {
  const known: Record<string, string> = {
    "tmux.create-window": "Create terminal window",
    "codex.start-session": "Start Codex session",
    "codex.send-prompt": "Send Codex prompt",
    "worker-send": "Run command in terminal",
  };
  if (known[use]) return known[use];
  return use.split(/[.:/_-]+/).filter(Boolean).map((part, index) => `${index === 0 ? part.charAt(0).toUpperCase() : part.charAt(0).toLowerCase()}${part.slice(1)}`).join(" ") || use;
}

function entryLabel(entry: CatalogEntry): string {
  return entry.presentation?.name && entry.presentation.name !== entry.use ? entry.presentation.name : friendlyUseLabel(entry.use ?? "action");
}

function TriggerNode({ data, selected }: NodeProps<GraphNode>) { return <div className={`flow-node trigger-node ${selected ? "selected" : ""}`}><Handle type="source" position={Position.Right} /><span className="node-kicker">TRIGGER</span><strong>{data.label}</strong><small>{data.use || "source"}</small></div>; }
function ActionNode({ data, selected }: NodeProps<GraphNode>) { const title = data.use === "cleanup" ? "Cleans all workers for the current source item; no upstream dependency required." : undefined; return <div className={`flow-node action-node ${selected ? "selected" : ""}`} title={title}><Handle type="target" position={Position.Left} /><Handle type="source" position={Position.Right} /><span className="node-kicker">ACTION</span><strong>{data.label}</strong><small>{data.use}</small>{data.status && <span className={statusClass(data.status)}>{data.status}</span>}</div>; }
const nodeTypes = { trigger: TriggerNode, action: ActionNode };

function App() {
  const [page, setPage] = useState<Page>("home");
  const [projects, setProjects] = useState<ProjectFolder[]>([]);
  const [project, setProject] = useState<ProjectFolder>();
  const [workflows, setWorkflows] = useState<WorkflowSummary[]>([]);
  const [executions, setExecutions] = useState<any[]>([]);
  const [workers, setWorkers] = useState<Worker[]>([]);
  const [plugins, setPlugins] = useState<Json>({ installed: [], referenced: [] });
  const [catalog, setCatalog] = useState<Json>({ schemas: {} });
  const [config, setConfig] = useState<Json>({});
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [registerOpen, setRegisterOpen] = useState(false);
  const refresh = useCallback(async (next = project) => {
    setLoading(true); setError("");
    try {
      const [folders, wfs, runs, ws, ps, cat] = await Promise.all([api.getProjects(), api.getWorkflows(next), api.getExecutions(next), api.getWorkers(next), api.getPlugins(next), api.getCatalog(next)]);
      setProjects(folders); if (!next && folders[0]) { setProject(folders[0]); } setWorkflows(wfs); setExecutions(runs); setWorkers(ws); setPlugins(ps); setCatalog(cat);
      try { setConfig((await api.getConfig(next)).config); } catch { /* the global API may not expose config yet */ }
    } catch (e) { setError(e instanceof Error ? e.message : String(e)); }
    finally { setLoading(false); }
  }, [project]);
  useEffect(() => { void refresh(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (project) void refresh(project); }, [project]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setInterval(() => { void Promise.all([api.getExecutions(project).then(setExecutions), api.getWorkers(project).then(setWorkers)]); }, 5000); return () => window.clearInterval(timer); }, [project]);
  const active = executions.filter((run) => ["running", "started", "launching", "claimed", "provisioning", "pending"].includes(run.status)).length;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">◆</span><div><b>task relay</b><small>control plane</small></div></div>
      <div className="workspace-label">WORKSPACE</div><select value={project?.id ?? ""} onChange={(event) => setProject(projects.find((entry) => entry.id === event.target.value))}><option value="">Current repository</option>{projects.map((entry) => <option key={entry.id} value={entry.id}>{entry.displayName || entry.root || entry.id}</option>)}</select>
      <nav>{nav.map((entry) => <button key={entry.id} className={page === entry.id ? "active" : ""} onClick={() => setPage(entry.id)}><span>{entry.icon}</span>{entry.label}{entry.id === "executions" && active > 0 && <em>{active}</em>}</button>)}</nav>
      <div className="sidebar-footer"><span className="online-dot" /> daemon connected <button className="icon-button" title="Refresh" onClick={() => void refresh()}>↻</button></div>
    </aside>
    <main className="main"><header><div><div className="breadcrumb">TASK RELAY / {project?.displayName || project?.root || "CURRENT REPOSITORY"}</div><h1>{nav.find((entry) => entry.id === page)?.label}</h1></div><div className="header-actions"><button className="button ghost" onClick={() => void refresh()}>↻ Refresh</button><button className="button primary" onClick={() => setRegisterOpen(true)}>+ Add repository</button></div></header>
      {error && <div className="alert error">{error}<button onClick={() => setError("")}>×</button></div>}
      {loading && !workflows.length && !executions.length ? <div className="loading"><span className="spinner" /> Loading control plane…</div> : <>{page === "home" && <HomePage workflows={workflows} executions={executions} workers={workers} projects={projects} onNavigate={setPage} />}{page === "repositories" && <Repositories projects={projects} selected={project} onSelect={(p) => { setProject(p); setPage("home"); }} onAdded={(p) => { setProjects((old) => [...old, p]); setProject(p); setRegisterOpen(false); }} onRemoved={(id) => { setProjects((old) => old.filter((entry) => entry.id !== id)); if (project?.id === id) setProject(undefined); }} />}{page === "workflows" && <Workflows workflows={workflows} config={config} catalog={catalog} project={project} onSaved={(next) => { setConfig(next); void refresh(project); }} />}{page === "executions" && <Executions executions={executions} workflows={workflows} onRefresh={() => void refresh(project)} />}{page === "workers" && <Workers workers={workers} project={project} />}{page === "plugins" && <Plugins plugins={plugins} catalog={catalog} />} </>}
    </main>{registerOpen && <RegisterDialog onClose={() => setRegisterOpen(false)} onAdded={(p) => { setProjects((old) => [...old, p]); setProject(p); setRegisterOpen(false); }} />}
  </div>;
}

function HomePage({ workflows, executions, workers, projects, onNavigate }: { workflows: WorkflowSummary[]; executions: any[]; workers: Worker[]; projects: ProjectFolder[]; onNavigate: (p: Page) => void }) {
  const failed = executions.filter((run) => run.status === "failed").length;
  return <div className="page-stack"><section className="hero"><div><span className="eyebrow">GLOBAL CONTROL PLANE</span><h2>Good morning, orchestrator.</h2><p>One view of every workflow, worker and repository in your relay network.</p></div><button className="button primary" onClick={() => onNavigate("workflows")}>Open workflow canvas →</button></section><div className="metric-grid"><Metric label="Running" value={executions.filter((run) => ["running", "started"].includes(run.status)).length} tone="green" /><Metric label="Failed" value={failed} tone="red" /><Metric label="Workers" value={workers.length} tone="purple" /><Metric label="Repositories" value={projects.length} tone="blue" /></div><div className="two-column"><section className="panel"><PanelTitle title="Live executions" action="View all" onClick={() => onNavigate("executions")} />{executions.slice(0, 5).map((run, index) => <ExecutionRow key={run.id ?? index} run={run} />)}{!executions.length && <Empty text="No executions yet" />}</section><section className="panel"><PanelTitle title="Workflows" action="Manage" onClick={() => onNavigate("workflows")} />{workflows.slice(0, 5).map((workflow) => <div className="list-row" key={workflow.id}><div className="list-icon workflow-icon">◇</div><div className="row-main"><b>{workflow.id}</b><small>{workflow.source || workflow.on?.source || "No source"}</small></div><span className={workflow.enabled === false ? "muted" : "status status-succeeded"}>{workflow.enabled === false ? "paused" : "enabled"}</span></div>)}{!workflows.length && <Empty text="No workflows configured" />}</section></div></div>;
}
function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className="metric"><span className={`metric-dot ${tone}`} /><div><b>{value}</b><small>{label}</small></div></div>; }
function PanelTitle({ title, action, onClick }: { title: string; action?: string; onClick?: () => void }) { return <div className="panel-title"><h3>{title}</h3>{action && <button className="text-button" onClick={onClick}>{action} →</button>}</div>; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
function ExecutionRow({ run }: { run: any }) { return <div className="list-row"><div className={`list-icon ${run.status === "failed" ? "failed-icon" : "run-icon"}`}>{run.status === "failed" ? "!" : "↗"}</div><div className="row-main"><b>{run.item?.id || run.id || "Execution"}</b><small>{run.item?.title || run.workflowId || run.identity?.workflowId || "Workflow execution"}</small></div><span className={statusClass(run.status)}>{run.status || "unknown"}</span><time>{time(run.updatedAt || run.startedAt || run.claimedAt)}</time></div>; }

function Repositories({ projects, selected, onSelect, onAdded, onRemoved }: { projects: ProjectFolder[]; selected?: ProjectFolder; onSelect: (p: ProjectFolder) => void; onAdded: (p: ProjectFolder) => void; onRemoved: (id: string) => void }) { const control = async (event: React.MouseEvent, project: ProjectFolder, action: "sync" | "start" | "stop") => { event.stopPropagation(); try { const result = await api.controlProject(project, action); window.alert(result.status?.error || result.status?.state || `${action} complete`); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); } }; const remove = async (event: React.MouseEvent, entry: ProjectFolder) => { event.stopPropagation(); if (!window.confirm(`Unregister '${entry.displayName || entry.root || entry.id}'? Files will not be deleted.`)) return; try { await api.removeProject(entry); onRemoved(entry.id); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); } }; return <div className="page-stack"><div className="section-intro"><div><span className="eyebrow">PROJECT FOLDERS</span><p>Each folder keeps its YAML authoritative while the registry provides the global index.</p></div><button className="button primary" onClick={() => { const root = window.prompt("Repository folder path"); if (root) api.registerProject(root).then(onAdded).catch((e) => window.alert(e.message)); }}>+ Register folder</button></div><div className="repository-grid">{projects.map((entry) => <div role="button" tabIndex={0} className={`repository-card ${selected?.id === entry.id ? "selected" : ""}`} key={entry.id} onClick={() => onSelect(entry)} onKeyDown={(event) => { if (event.key === "Enter") onSelect(entry); }}><div className="repo-card-head"><span className="repo-icon">▣</span><span className="status status-succeeded">{entry.enabled === false ? "disabled" : "connected"}</span></div><h3>{entry.displayName || entry.id}</h3><code>{entry.root || "Current working directory"}</code><div className="repo-meta"><span>{entry.configStatus || "configuration loaded"}</span><span className="repo-controls"><button onClick={(event) => void control(event, entry, "sync")}>Sync</button><button onClick={(event) => void control(event, entry, "start")}>Start</button><button onClick={(event) => void control(event, entry, "stop")}>Stop</button><button className="danger-link" onClick={(event) => void remove(event, entry)}>Remove</button></span></div></div>)}</div>{!projects.length && <Empty text="Register a repository folder to get started." />}<RegisterInline onAdded={onAdded} /></div>; }
function RegisterInline({ onAdded }: { onAdded: (p: ProjectFolder) => void }) { const [value, setValue] = useState(""); return <div className="register-inline"><input placeholder="/path/to/repository" value={value} onChange={(e) => setValue(e.target.value)} /><button className="button ghost" disabled={!value} onClick={() => api.registerProject(value).then((p) => { setValue(""); onAdded(p); }).catch((e) => window.alert(e.message))}>Register path</button></div>; }
function RegisterDialog({ onClose, onAdded }: { onClose: () => void; onAdded: (p: ProjectFolder) => void }) { const [value, setValue] = useState(""); return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Add repository</h2><button className="icon-button" onClick={onClose}>×</button></div><p>Register a local Git folder with the global control plane.</p><input autoFocus placeholder="/Users/me/Development/project" value={value} onChange={(e) => setValue(e.target.value)} /><div className="modal-actions"><button className="button ghost" onClick={onClose}>Cancel</button><button className="button primary" disabled={!value.trim()} onClick={() => api.registerProject(value.trim()).then(onAdded).catch((e) => window.alert(e.message))}>Register folder</button></div></div></div>; }

function Workflows({ workflows, config, catalog, project, onSaved }: { workflows: WorkflowSummary[]; config: Json; catalog: Json; project?: ProjectFolder; onSaved: (config: Json) => void }) {
  const [selected, setSelected] = useState(workflows[0]?.id ?? "");
  const [draft, setDraft] = useState<WorkflowSummary>();
  useEffect(() => {
    if (selected && (workflows.some((workflow) => workflow.id === selected) || draft?.id === selected)) return;
    setSelected(workflows[0]?.id ?? "");
  }, [workflows, selected, draft]);
  const create = () => {
    if (!project) return window.alert("Register and select a repository first.");
    const id = window.prompt("Workflow id", "cleanup-on-done")?.trim();
    if (!id) return;
    if (!/^[a-zA-Z0-9._:-]+$/.test(id) || workflows.some((workflow) => workflow.id === id)) return window.alert("Use a unique workflow id containing letters, numbers, '.', '_', ':' or '-'.");
    const source = Object.keys(config.sources ?? {})[0];
    if (!source) return window.alert("Configure a source before creating a workflow.");
    // New workflows are terminal-cleanup workflows by default: a Done item is
    // scoped to its own repository/source/item and cleans every Relay-owned
    // tmux worker plus its worktree. The canvas remains fully editable.
    const next: WorkflowSummary = { id, enabled: true, on: { source, match: { statusTypes: ["completed"] }, fire: { policy: "once-per-match" } }, source, targets: { workers: { sourceItem: "current", runs: "all" } }, jobs: { cleanup: { use: "cleanup", with: { activeWorker: "stop", ownedTmuxOnly: true } } }, timeoutMinutes: 1440 };
    setDraft(next); setSelected(id);
  };
  const summary = workflows.find((workflow) => workflow.id === selected) ?? (draft?.id === selected ? draft : undefined);
  const current = summary ? { ...summary, ...(config.workflows?.[selected] ?? {}), id: selected } as WorkflowSummary : undefined;
  return <div className="workflow-layout"><aside className="workflow-list"><div className="list-head"><h3>Workflows</h3><button className="icon-button" title="New workflow" onClick={create}>＋</button></div>{workflows.map((workflow) => <button key={workflow.id} className={workflow.id === selected ? "workflow-item selected" : "workflow-item"} onClick={() => { setDraft(undefined); setSelected(workflow.id); }}><span className="workflow-status" /><span><b>{workflow.id}</b><small>{Object.keys(workflow.jobs ?? {}).length} jobs · {workflow.enabled === false ? "paused" : "active"}</small></span></button>)}{draft && !workflows.some((workflow) => workflow.id === draft.id) && <button className="workflow-item selected"><span className="workflow-status" /><span><b>{draft.id}</b><small>unsaved draft</small></span></button>}{!workflows.length && !draft && <Empty text="No workflows" />}</aside>{current ? <WorkflowEditor key={current.id} workflow={current} config={config} catalog={catalog} project={project} onSaved={(next) => { setDraft(undefined); onSaved(next); }} /> : <div className="editor-empty"><div className="empty-graphic">◇</div><h2>Select a workflow</h2><p>Create or select a workflow to open the canvas.</p><button className="button primary" onClick={create}>Create workflow</button></div>}</div>;
}

function WorkflowEditor({ workflow, config, catalog, project, onSaved }: { workflow: WorkflowSummary; config: Json; catalog: Json; project?: ProjectFolder; onSaved: (config: Json) => void }) {
  const schemas: Record<string, any> = useMemo(() => {
    const values: Record<string, any> = {};
    for (const entry of catalogEntries(catalog)) {
      if (!entry.use || !entry.kind) continue;
      const value = { ...entry, schema: entrySchema(entry, entry.kind) };
      values[`${entry.kind}:${entry.use}`] = value;
      // Existing dashboard code addresses action/source schemas by short use.
      if (!(entry.use in values) || entry.kind === "action") values[entry.use] = value;
    }
    // Keep the editor usable while an older server is still warming its
    // catalog endpoint; these built-ins are valid Relay action identifiers.
    for (const use of ["launch", "cleanup", "command", "worker-exec", "worker-send"]) {
      if (!values[`action:${use}`] && !values[use]) values[`action:${use}`] = { use, kind: "action", schema: { type: "object", properties: {} }, presentation: { name: friendlyUseLabel(use) } };
    }
    for (const [sourceId, source] of Object.entries(config.sources ?? {}) as Array<[string, any]>) {
      const plugin = values[`source:${source.use}`] ?? values[source.use];
      values[`source:${sourceId}`] = { ...(plugin ?? { kind: "source", schema: { type: "object", properties: {} } }), kind: "source", use: sourceId, configured: true, schema: entrySchema(plugin, "source") ?? { type: "object", properties: {} }, presentation: { ...(plugin?.presentation ?? {}), name: sourceId, description: `Configured ${source.use} source` } };
    }
    return values;
  }, [catalog, config.sources]);
  const initial = useMemo(() => workflowToGraph(workflow, schemas), [workflow, schemas]);
  const [nodes, setNodes, onNodesChange] = useNodesState<GraphNode>(initial.nodes); const [edges, setEdges, onEdgesChange] = useEdgesState(initial.edges); const [viewport, setViewport] = useState<Viewport>({ x: 0, y: 0, zoom: 1 }); const [loadedMtime, setLoadedMtime] = useState(0);
  const [selectedNode, setSelectedNode] = useState<GraphNode>(); const [paletteOpen, setPaletteOpen] = useState(false); const [rawOpen, setRawOpen] = useState(false); const [raw, setRaw] = useState(""); const [message, setMessage] = useState(""); const [actionTest, setActionTest] = useState<ActionTestResult>(); const [testingAction, setTestingAction] = useState(false);
  const history = useRef<{ nodes: GraphNode[]; edges: Edge[] }[]>([]); const future = useRef<{ nodes: GraphNode[]; edges: Edge[] }[]>([]); const dragSnapshot = useRef<{ nodes: GraphNode[]; edges: Edge[] } | undefined>(undefined); const snapshot = () => ({ nodes: structuredClone(nodes), edges: structuredClone(edges) });
  useEffect(() => { void api.getLayout(workflow.id, project).then((layout) => { const saved = layout?.nodes && !Array.isArray(layout.nodes) ? Object.entries(layout.nodes).map(([id, position]) => ({ id, ...(position as object) })) : (layout?.nodes ?? layout); if (layout?.viewport) setViewport(layout.viewport as Viewport); if (!Array.isArray(saved)) return; setNodes((current) => current.map((node) => { const position = saved.find((item: any) => item.id === node.id); return position ? { ...node, position: { x: position.x ?? node.position.x, y: position.y ?? node.position.y } } : node; })); }); void api.getConfigMtime(project).then(setLoadedMtime); }, [workflow.id, project]);
  const commit = (nextNodes: GraphNode[], nextEdges: Edge[]) => { history.current.push(snapshot()); future.current = []; setNodes(nextNodes); setEdges(nextEdges); };
  const connect = useCallback((connection: Connection) => { if (!connection.source || !connection.target || wouldCycle(edges, connection.source, connection.target)) { setMessage("That connection would create a cycle."); return; } commit(nodes, addEdge({ ...connection, type: "smoothstep", label: "succeeded" }, edges)); }, [nodes, edges]);
  const reconnect = useCallback((oldEdge: Edge, connection: Connection) => { if (!connection.source || !connection.target || wouldCycle(edges.filter((edge) => edge.id !== oldEdge.id), connection.source, connection.target)) { setMessage("That reconnection would create a cycle."); return; } commit(nodes, reconnectEdge(oldEdge, connection, edges)); }, [nodes, edges]);
  const editEdge = useCallback((_: unknown, edge: Edge) => { const condition = window.prompt("Dependency condition: succeeded, failed, started, or skipped", String(edge.label || "succeeded"))?.trim().toLowerCase(); if (!condition) return; if (!["succeeded", "failed", "started", "skipped"].includes(condition)) { setMessage("Unknown dependency condition."); return; } commit(nodes, edges.map((entry) => entry.id === edge.id ? { ...entry, label: condition } : entry)); }, [nodes, edges]);
  const selectNode = useCallback((_: any, node: GraphNode) => { setSelectedNode(node); setActionTest(undefined); setPaletteOpen(false); }, []);
  const updateNode = (data: Partial<GraphNodeData>) => { if (!selectedNode) return; const next = nodes.map((node) => node.id === selectedNode.id ? { ...node, data: { ...node.data, ...data } } : node); history.current.push(snapshot()); future.current = []; setNodes(next); setSelectedNode(next.find((node) => node.id === selectedNode.id)); };
  const updateActionReference = (path: string, actionId?: string) => {
    if (!selectedNode || selectedNode.data.kind !== "action") return;
    const reference = actionReferenceFor(selectedNode.data.use);
    const previousActionId = reference ? actionReferenceValue(selectedNode.data.config, path, reference.value) : undefined;
    const config = setActionReference(selectedNode.data.config ?? {}, path, actionId, reference?.value);
    const nextNodes = nodes.map((node) => node.id === selectedNode.id ? { ...node, data: { ...node.data, config } } : node);
    const nextEdges = syncActionReferenceEdge(edges, selectedNode.id, path, typeof previousActionId === "string" ? previousActionId : undefined, actionId);
    history.current.push(snapshot()); future.current = []; setNodes(nextNodes); setEdges(nextEdges); setSelectedNode(nextNodes.find((node) => node.id === selectedNode.id));
  };
  const changeActionUse = (nextUse: string) => {
    if (!selectedNode) return;
    const previousReference = actionReferenceFor(selectedNode.data.use);
    let nextEdges = edges;
    if (previousReference) {
      const previousActionId = actionReferenceValue(selectedNode.data.config, previousReference.path, previousReference.value);
      nextEdges = syncActionReferenceEdge(nextEdges, selectedNode.id, previousReference.path, typeof previousActionId === "string" ? previousActionId : undefined, undefined);
    }
    const nextSchema = schemas[`action:${nextUse}`] ?? schemas[nextUse];
    const nextNodes = nodes.map((node) => node.id === selectedNode.id ? { ...node, data: { ...node.data, use: nextUse, schema: entrySchema(nextSchema), config: { use: nextUse, with: {} } } } : node);
    history.current.push(snapshot()); future.current = []; setNodes(nextNodes); setEdges(nextEdges); setSelectedNode(nextNodes.find((node) => node.id === selectedNode.id));
  };
  const undo = () => { const previous = history.current.pop(); if (!previous) return; future.current.push(snapshot()); setNodes(previous.nodes); setEdges(previous.edges); setSelectedNode(undefined); }; const redo = () => { const next = future.current.pop(); if (!next) return; history.current.push(snapshot()); setNodes(next.nodes); setEdges(next.edges); };
  const addAction = (use: string) => { const id = `${use.split(/[/:]/).pop() || "action"}-${nodes.filter((n) => n.data.kind === "action").length + 1}`; const node: GraphNode = { id, type: "action", position: { x: 400, y: 200 + nodes.length * 20 }, data: { label: id, use, kind: "action", config: { use, with: {} }, schema: (schemas[`action:${use}`] ?? schemas[use])?.schema } }; commit([...nodes, node], edges); setSelectedNode(node); setPaletteOpen(false); };
  const deleteNode = () => { if (!selectedNode || selectedNode.data.kind === "trigger") return; const deletedId = selectedNode.id; const nextNodes = nodes.filter((node) => node.id !== deletedId).map((node) => { const reference = node.data.kind === "action" ? actionReferenceFor(node.data.use) : undefined; return reference && actionReferenceValue(node.data.config, reference.path, reference.value) === deletedId ? { ...node, data: { ...node.data, config: setActionReference(node.data.config, reference.path, undefined, reference.value) } } : node; }); commit(nextNodes, edges.filter((edge) => edge.source !== deletedId && edge.target !== deletedId)); setSelectedNode(undefined); };
  const danglingEdges = findDanglingEdges(nodes, edges);
  const danglingReferences = findDanglingActionReferences(nodes);
  const danglingMessage = () => { const edge = danglingEdges[0]; if (edge) return `Cannot continue: dependency points to missing node '${!nodes.some((node) => node.id === edge.source) ? edge.source : edge.target}'. Reconnect or delete the dangling edge.`; const reference = danglingReferences[0]; return reference ? `Cannot continue: action '${reference.nodeId}' references missing or incompatible action '${reference.actionId}'. Select a valid upstream action or clear the reference.` : undefined; };
  const save = async () => { try { const dangling = danglingMessage(); if (dangling) { setMessage(dangling); return; } const currentMtime = await api.getConfigMtime(project); if (loadedMtime && currentMtime && currentMtime !== loadedMtime) { setMessage("Configuration changed on disk. Reload before saving to avoid overwriting YAML."); return; } const nextWorkflow = graphToWorkflow({ nodes, edges }, workflow); const next = { ...config, workflows: { ...(config.workflows ?? {}), [workflow.id]: nextWorkflow } }; const isNew = !Object.prototype.hasOwnProperty.call(config.workflows ?? {}, workflow.id); try { const result = isNew ? await api.createWorkflow(workflow.id, nextWorkflow as Json, project) : await api.saveWorkflow(workflow.id, nextWorkflow as Json, project, workflow.revision); if (result?.workflow?.revision) nextWorkflow.revision = result.workflow.revision; } catch (error) { if (!(error instanceof api.ApiError) || ![404, 501].includes(error.status)) throw error; await api.saveConfig(next, project); } await api.saveLayout(workflow.id, { nodes: nodes.map((node) => ({ id: node.id, x: node.position.x, y: node.position.y })), viewport }, project).catch(() => undefined); onSaved(next); setLoadedMtime(await api.getConfigMtime(project) || currentMtime); setMessage("Saved to YAML"); } catch (e) { setMessage(`Save failed: ${e instanceof Error ? e.message : String(e)}`); } };
  const test = async () => { try { const dangling = danglingMessage(); if (dangling) { setMessage(dangling); return; } const result = await api.testWorkflow(workflow.id, project); setMessage(result.output ? String(result.output) : "Dry run complete"); } catch (e) { setMessage(`Test failed: ${e instanceof Error ? e.message : String(e)}`); } };
  const testSelectedAction = async () => {
    if (!selectedNode || selectedNode.data.kind !== "action") return;
    const dangling = danglingMessage();
    if (dangling) { setMessage(dangling); return; }
    setTestingAction(true); setActionTest(undefined); setMessage("");
    try {
      const draftWorkflow = graphToWorkflow({ nodes, edges }, workflow);
      const result = await api.testAction(workflow.id, selectedNode.id, project, { workflow: draftWorkflow as Json, action: { id: selectedNode.id, use: selectedNode.data.use, ...selectedNode.data.config } });
      setActionTest(result);
    } catch (e) {
      setMessage(`Action test failed: ${e instanceof Error ? e.message : String(e)}`);
    } finally { setTestingAction(false); }
  };
  const duplicate = async () => { const id = window.prompt("Duplicate workflow as", `${workflow.id}-copy`)?.trim(); if (!id || !project) return; if (!/^[a-zA-Z0-9._:-]+$/.test(id)) { setMessage("Use a valid workflow id."); return; } try { const value = graphToWorkflow({ nodes, edges }, { ...workflow, id }); try { await api.createWorkflow(id, value as Json, project); } catch (error) { if (!(error instanceof api.ApiError) || ![404, 501].includes(error.status)) throw error; await api.saveConfig({ ...config, workflows: { ...(config.workflows ?? {}), [id]: value } }, project); } const next = { ...config, workflows: { ...(config.workflows ?? {}), [id]: value } }; onSaved(next); } catch (error) { setMessage(`Duplicate failed: ${error instanceof Error ? error.message : String(error)}`); } };
  const rename = async () => { const id = window.prompt("Rename workflow", workflow.id)?.trim(); if (!id || id === workflow.id || !project) return; if (!/^[a-zA-Z0-9._:-]+$/.test(id)) { setMessage("Use a valid workflow id."); return; } try { const workflows = { ...(config.workflows ?? {}) }; workflows[id] = workflows[workflow.id] ?? graphToWorkflow({ nodes, edges }, workflow); delete workflows[workflow.id]; try { await api.renameWorkflow(workflow.id, id, project, workflow.revision); } catch (error) { if (!(error instanceof api.ApiError) || ![404, 501].includes(error.status)) throw error; await api.saveConfig({ ...config, workflows }, project); } onSaved({ ...config, workflows }); } catch (error) { setMessage(`Rename failed: ${error instanceof Error ? error.message : String(error)}`); } };
  const remove = async () => { if (!project || !window.confirm(`Delete workflow '${workflow.id}'?`)) return; try { const workflows = { ...(config.workflows ?? {}) }; delete workflows[workflow.id]; try { await api.deleteWorkflow(workflow.id, project, workflow.revision); } catch (error) { if (!(error instanceof api.ApiError) || ![404, 501].includes(error.status)) throw error; await api.saveConfig({ ...config, workflows }, project); } onSaved({ ...config, workflows }); } catch (error) { setMessage(`Delete failed: ${error instanceof Error ? error.message : String(error)}`); } };
  const onNodesDelete = (deleted: GraphNode[]) => { const ids = new Set(deleted.map((node) => node.id)); const nextNodes = nodes.filter((node) => !ids.has(node.id)).map((node) => { const reference = node.data.kind === "action" ? actionReferenceFor(node.data.use) : undefined; const actionId = reference ? actionReferenceValue(node.data.config, reference.path, reference.value) : undefined; return reference && actionId && ids.has(actionId) ? { ...node, data: { ...node.data, config: setActionReference(node.data.config, reference.path, undefined, reference.value) } } : node; }); const nextEdges = edges.filter((edge) => !ids.has(edge.source) && !ids.has(edge.target)); commit(nextNodes, nextEdges); if (selectedNode && ids.has(selectedNode.id)) setSelectedNode(undefined); };
  const onNodeDragStart = () => { dragSnapshot.current = snapshot(); };
  const onNodeDragStop = () => { if (dragSnapshot.current) { history.current.push(dragSnapshot.current); future.current = []; dragSnapshot.current = undefined; } };
  return <section className="editor"><div className="editor-toolbar"><div><h2>{workflow.id}</h2><span className="muted">{workflow.enabled === false ? "Paused" : "Enabled"} · {nodes.length - 1} actions</span></div><div className="toolbar-actions"><button className="button ghost" onClick={undo} disabled={!history.current.length}>↶</button><button className="button ghost" onClick={redo} disabled={!future.current.length}>↷</button><button className="button ghost" onClick={() => { const next = autoLayout(nodes, edges); commit(next, edges); }}>Auto-layout</button><button className="button ghost" onClick={duplicate}>Duplicate</button><button className="button ghost" onClick={rename}>Rename</button><button className="button ghost" onClick={remove}>Delete</button><button className="button ghost" onClick={test}>Test</button><button className="button primary" onClick={save}>Save workflow</button></div></div>{message && <div className="editor-message">{message}<button onClick={() => setMessage("")}>×</button></div>}<div className="canvas-wrap"><ReactFlowProvider><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onNodesDelete={onNodesDelete} onNodeDragStart={onNodeDragStart} onNodeDragStop={onNodeDragStop} onEdgesChange={onEdgesChange} onConnect={connect} onReconnect={reconnect} onEdgeDoubleClick={editEdge} onMoveEnd={(_, nextViewport) => setViewport(nextViewport)} onNodeClick={selectNode} fitView proOptions={{ hideAttribution: true }}><Background color="#273244" gap={24} /><Controls /><MiniMap nodeColor={(node) => node.type === "trigger" ? "#8b5cf6" : "#239b8d"} /></ReactFlow></ReactFlowProvider><button className="add-node-button" onClick={() => setPaletteOpen((open) => !open)}>＋ Add node</button>{paletteOpen && <NodePalette schemas={schemas} onAdd={addAction} />}</div>{selectedNode && <PropertyPanel node={selectedNode} nodes={nodes} edges={edges} schemas={schemas} onChange={updateNode} onActionReferenceChange={updateActionReference} onActionUseChange={changeActionUse} onDelete={deleteNode} onClose={() => setSelectedNode(undefined)} onRaw={() => { setRaw(JSON.stringify(selectedNode.data.config ?? {}, null, 2)); setRawOpen(true); }} onTestAction={testSelectedAction} testingAction={testingAction} actionTest={actionTest} />}{rawOpen && <RawDialog value={raw} onChange={setRaw} onClose={() => setRawOpen(false)} onApply={() => { try { updateNode({ config: JSON.parse(raw) }); setRawOpen(false); setMessage("Node configuration updated"); } catch { setMessage("Invalid JSON configuration"); } }} />}</section>;
}

function NodePalette({ schemas, onAdd }: { schemas: Record<string, any>; onAdd: (use: string) => void }) {
  const entries = Object.values(schemas).filter((entry: CatalogEntry, index, all) => entry.kind === "action" && Boolean(entry.use) && all.findIndex((candidate: CatalogEntry) => candidate.kind === "action" && candidate.use === entry.use) === index);
  return <div className="node-palette"><span className="eyebrow">NODE CATALOG</span>{entries.length ? entries.map((entry) => <button key={entry.use} title={entry.presentation?.description} onClick={() => onAdd(entry.use!)}><span className="palette-dot" />{entryLabel(entry)}<small>{entry.health || entry.presentation?.category || "action"}</small></button>) : <small className="palette-empty">No actions available in the catalog.</small>}</div>;
}

function PropertyPanel({ node, nodes, edges, schemas, onChange, onActionReferenceChange, onActionUseChange, onDelete, onClose, onRaw, onTestAction, testingAction, actionTest }: { node: GraphNode; nodes: GraphNode[]; edges: Edge[]; schemas: Record<string, any>; onChange: (data: Partial<GraphNodeData>) => void; onActionReferenceChange: (path: string, actionId?: string) => void; onActionUseChange: (use: string) => void; onDelete: () => void; onClose: () => void; onRaw: () => void; onTestAction: () => void; testingAction: boolean; actionTest?: ActionTestResult }) {
  const key = `${node.data.kind === "trigger" ? "source" : "action"}:${node.data.use}`;
  const schema = node.data.schema ?? entrySchema(schemas[key] ?? schemas[node.data.use], node.data.kind === "trigger" ? "source" : "action");
  const properties = schema?.properties ?? {};
  const config = node.data.config ?? {};
  const kind = node.data.kind === "trigger" ? "source" : "action";
  const entries = Object.values(schemas).filter((entry: CatalogEntry, index, all) => entry.kind === kind && (kind !== "source" || (entry as CatalogEntry & { configured?: boolean }).configured) && Boolean(entry.use) && all.findIndex((candidate: CatalogEntry) => candidate.kind === kind && (kind !== "source" || (candidate as CatalogEntry & { configured?: boolean }).configured) && candidate.use === entry.use) === index);
  const fieldValue = (name: string) => node.data.kind === "trigger" ? config[name] : (config.with ?? config)[name];
  const setField = (name: string, value: any) => onChange({ config: node.data.kind === "trigger" ? { ...config, [name]: value } : { ...config, with: { ...(config.with ?? {}), [name]: value } } });
  const setActionField = (name: string, value: any) => onChange({ config: { ...config, [name]: value } });
  const reference = node.data.kind === "action" ? actionReferenceFor(node.data.use) : undefined;
  const selectedReference = reference ? actionReferenceValue(config, reference.path, reference.value) : undefined;
  const referenceCandidates = reference ? upstreamReferenceNodes(nodes, edges, node.id, reference.upstreamUse) : [];
  const currentReferenceNode = selectedReference ? nodes.find((candidate) => candidate.id === selectedReference) : undefined;
  const referenceOptions = currentReferenceNode && !referenceCandidates.some((candidate) => candidate.id === currentReferenceNode.id) ? [...referenceCandidates, currentReferenceNode] : referenceCandidates;
  const referenceRoot = reference?.path.split(".")[0];
  const visibleProperties = Object.entries(properties).filter(([name]) => name !== reference?.path && name !== referenceRoot);
  const cleanupHelp = node.data.kind === "action" && node.data.use === "cleanup" ? "Cleans all workers for the current source item. This standalone action does not require an upstream dependency." : undefined;
  return <aside className="property-panel"><div className="panel-title"><h3>{node.data.kind === "trigger" ? "Trigger settings" : "Action settings"}</h3><button className="icon-button" onClick={onClose}>×</button></div><label>Display name<input value={node.data.label} onChange={(e) => onChange({ label: e.target.value })} /></label><label>{node.data.kind === "trigger" ? "Source" : "Action"}<select value={node.data.use} onChange={(e) => node.data.kind === "action" ? onActionUseChange(e.target.value) : onChange({ use: e.target.value, schema: entrySchema(schemas[`${kind}:${e.target.value}`] ?? schemas[e.target.value]), config: {} })}>{entries.map((entry) => <option key={entry.use} value={entry.use}>{entryLabel(entry)}</option>)}</select></label>{reference && <label className="reference-field">{reference.label}<select aria-label={reference.label} value={selectedReference ?? ""} onChange={(e) => onActionReferenceChange(reference.path, e.target.value || undefined)}><option value="">Select a preceding action…</option>{referenceOptions.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.data.label} · {candidate.data.use}{candidate.id === selectedReference && !referenceCandidates.some((entry) => entry.id === candidate.id) ? " (current)" : ""}</option>)}</select><small className="field-help">Uses the output from a preceding {friendlyUseLabel(reference.upstreamUse).toLowerCase()} action and adds its dependency automatically.</small></label>}{node.data.kind === "action" && <><label>Run condition (if)<input value={config.if ?? ""} placeholder="${{ item.metadata.priority == 'high' }}" onChange={(e) => setActionField("if", e.target.value || undefined)} /></label><label className="check-label"><input type="checkbox" checked={config.enabled !== false} onChange={(e) => setActionField("enabled", e.target.checked)} /> Enabled</label></>}<div className="property-divider" />{visibleProperties.length ? visibleProperties.map(([name, definition]: [string, any]) => <SchemaField key={name} name={name} definition={definition} value={fieldValue(name)} onChange={(value) => setField(name, value)} />) : !reference && <small className="field-help">No typed fields are provided for this action. Use raw JSON for plugin-specific configuration.</small>}{node.data.kind === "action" && <><button className="button primary full" onClick={onTestAction} disabled={testingAction}>{testingAction ? "Testing action…" : "Test action"}</button>{actionTest && <ActionTestResultPanel result={actionTest} />}</>}<button className="button ghost full" onClick={onRaw}>Edit raw JSON</button>{node.data.kind === "action" && <button className="button danger full" onClick={onDelete}>Delete node</button>}</aside>;
}
function ActionTestResultPanel({ result }: { result: ActionTestResult }) { const triggerCount = result.triggerMatchCount; const eligibleCount = result.eligibleCount; const headline = triggerCount !== eligibleCount ? `${eligibleCount} of ${triggerCount} tickets can run this action now` : `${eligibleCount} ticket${eligibleCount === 1 ? "" : "s"} can run this action now`; return <section className="action-test-result" aria-live="polite"><div className="action-test-heading"><span className="eyebrow">DRY RUN</span><b>{headline}</b></div>{result.matches.length > 0 ? <div className="action-test-matches">{result.matches.map((match, index) => { const eligible = match.eligible !== false && match.decision !== "ineligible" && match.decision !== "skipped" && match.decision !== "blocked"; return <div className={`action-test-match ${eligible ? "eligible" : "ineligible"}`} key={`${match.id ?? "match"}-${index}`}><div><b>{match.id || "Untitled ticket"}</b>{match.title && <small>{match.title}</small>}</div><span>{eligible ? "eligible" : "ineligible"}</span>{!eligible && (match.reason || match.decision) && <small className="action-test-reason">{match.reason || match.decision}</small>}</div>; })}</div> : <p className="action-test-empty">No tickets matched the trigger conditions.</p>}{result.reasons.length > 0 && <div className="action-test-reasons"><small>Notes</small>{result.reasons.map((reason, index) => <span key={`${reason}-${index}`}>{reason}</span>)}</div>}</section>; }
function SchemaField({ name, definition, value, onChange }: { name: string; definition: any; value: any; onChange: (value: any) => void }) { const title = definition.title || name.replace(/[-_]/g, " "); const effectiveValue = value ?? definition.default; if (definition.enum) return <label>{title}<select value={effectiveValue ?? ""} onChange={(e) => onChange(e.target.value)}><option value="">Select…</option>{definition.enum.map((option: string) => <option key={option}>{option}</option>)}</select></label>; if (definition.type === "boolean") return <label className="check-label"><input type="checkbox" checked={Boolean(effectiveValue)} onChange={(e) => onChange(e.target.checked)} /> {title}</label>; if (definition.type === "object" || definition.type === "array") return <label>{title}{definition.description && <small className="field-help">{definition.description}</small>}<textarea className="schema-json-field" value={value === undefined ? "" : JSON.stringify(value, null, 2)} placeholder={definition.type === "array" ? "[]" : "{}"} onChange={(e) => { try { onChange(e.target.value.trim() ? JSON.parse(e.target.value) : undefined); } catch { /* keep editing invalid JSON until it parses */ } }} /></label>; const numeric = definition.type === "integer" || definition.type === "number"; return <label>{title}{definition.description && <small className="field-help">{definition.description}</small>}<input type={numeric ? "number" : "text"} value={value ?? ""} placeholder={definition.default ?? ""} onChange={(e) => onChange(numeric && e.target.value !== "" ? Number(e.target.value) : e.target.value)} /></label>; }
function RawDialog({ value, onChange, onClose, onApply }: { value: string; onChange: (value: string) => void; onClose: () => void; onApply: () => void }) { return <div className="modal-backdrop"><div className="modal raw-modal"><div className="modal-head"><h2>Raw node configuration</h2><button className="icon-button" onClick={onClose}>×</button></div><textarea value={value} onChange={(e) => onChange(e.target.value)} spellCheck={false} /><div className="modal-actions"><button className="button ghost" onClick={onClose}>Cancel</button><button className="button primary" onClick={onApply}>Apply</button></div></div></div>; }

function Executions({ executions, workflows, onRefresh }: { executions: any[]; workflows: WorkflowSummary[]; onRefresh: () => void }) { const [filter, setFilter] = useState("all"); const [busy, setBusy] = useState(""); const visible = executions.filter((run) => filter === "all" || run.status === filter); const inspect = async (run: any) => { try { const detail = await api.getExecution(run.id); window.alert(JSON.stringify(detail, null, 2)); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); } }; const retry = async (run: any) => { setBusy(run.id); try { await api.retryExecution(run.id); onRefresh(); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); } finally { setBusy(""); } }; return <div className="page-stack"><div className="section-intro"><div><span className="eyebrow">GLOBAL EXECUTION LOG</span><p>Live state indexed across every registered repository.</p></div><select className="filter-select" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All statuses</option>{["running", "pending", "succeeded", "failed", "stopped"].map((status) => <option key={status}>{status}</option>)}</select></div><section className="panel table-panel"><table><thead><tr><th>Work item</th><th>Workflow</th><th>Status</th><th>Updated</th><th>Jobs</th><th>Actions</th></tr></thead><tbody>{visible.map((run, index) => <tr key={run.id ?? index}><td><b>{run.item?.id || run.id || "—"}</b><small>{run.item?.title || ""}</small></td><td>{run.identity?.workflowId || run.workflowId || workflows.find((w) => w.runs?.some((item) => item.id === run.id))?.id || "—"}</td><td><span className={statusClass(run.status)}>{run.status || "unknown"}</span></td><td>{time(run.updatedAt || run.startedAt)}</td><td>{run.jobs ? Object.keys(run.jobs).length : "—"}</td><td><button className="small-button" onClick={() => void inspect(run)}>Inspect</button>{run.status === "failed" && <button className="small-button" disabled={busy === run.id} onClick={() => void retry(run)}>Retry</button>}</td></tr>)}</tbody></table>{!visible.length && <Empty text="No executions match this filter." />}</section></div>; }
function Workers({ workers, project }: { workers: Worker[]; project?: ProjectFolder }) { const [busy, setBusy] = useState(""); const control = async (worker: Worker, action: "send" | "exec") => { const text = window.prompt(action === "send" ? "Prompt to send" : "Command to execute"); if (!text) return; setBusy(worker.id); try { await api.controlWorker(worker.id, action, action === "send" ? { text } : { command: text }, project); } catch (e) { window.alert(e instanceof Error ? e.message : String(e)); } finally { setBusy(""); } }; return <div className="page-stack"><div className="section-intro"><div><span className="eyebrow">WORKER POOL</span><p>Interactive agents launched by Relay workflows.</p></div></div><section className="panel table-panel"><table><thead><tr><th>Worker</th><th>Status</th><th>Task</th><th>Workspace</th><th>Controls</th></tr></thead><tbody>{workers.map((worker, index) => <tr key={worker.id ?? index}><td><b>{worker.id}</b></td><td><span className={statusClass(worker.status)}>{worker.status || "unknown"}</span></td><td>{worker.task || worker.title || "—"}</td><td><code>{worker.workspace?.path || "—"}</code></td><td><button className="small-button" disabled={busy === worker.id} onClick={() => void control(worker, "send")}>Send</button><button className="small-button" disabled={busy === worker.id} onClick={() => void control(worker, "exec")}>Pane</button></td></tr>)}</tbody></table>{!workers.length && <Empty text="No workers indexed yet." />}</section></div>; }
function Plugins({ plugins, catalog }: { plugins: Json; catalog: Json }) { const installed = plugins.installed ?? []; const referenced = plugins.referenced ?? []; const schemas = catalog.schemas ?? catalog; return <div className="page-stack"><div className="section-intro"><div><span className="eyebrow">EXTENSION CATALOG</span><p>Triggers, actions and harnesses are described by JSON Schema.</p></div><span className="catalog-count">{Object.keys(schemas).length} catalog entries</span></div><div className="two-column"><section className="panel"><PanelTitle title="Installed plugins" />{installed.map((plugin: any) => <div className="list-row" key={plugin.package || plugin.name || plugin.use || plugin.id}><div className="list-icon plugin-icon">⬡</div><div className="row-main"><b>{plugin.package || plugin.name || plugin.use || plugin.id || "Plugin"}</b><small>{plugin.version || plugin.health || "local"}</small></div><span className="status status-succeeded">ready</span></div>)}{!installed.length && <Empty text="No external plugins installed." />}</section><section className="panel"><PanelTitle title="Referenced health" />{referenced.map((plugin: any) => <div className="list-row" key={plugin.use}><div className="list-icon plugin-icon">⬡</div><div className="row-main"><b>{plugin.use}</b><small>{(plugin.locations ?? []).join(", ")}</small></div><span className={statusClass(plugin.state)}>{plugin.state}</span></div>)}{!referenced.length && <Empty text="Only built-in plugins referenced." />}</section></div></div>; }

export default function RootApp() { return <ReactFlowProvider><App /></ReactFlowProvider>; }
